version: 2
jobs:
  package:
    working_directory: /workdir
    docker:
      - image: docker:17.06.0-ce-git
        environment:
          CHART_URL: https://charts.bitnami.com

    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Upgrade system packages (workaround - https://github.com/docker-library/docker/issues/72)
          command: |
            apk upgrade --no-cache
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache bash curl
      - run:
          name: Package charts
          command: |
            curl -sL https://raw.githubusercontent.com/tompizmor/test-infra/chart_repo_branches/circle/helm-package-charts.sh | bash -
      - deploy:
          name: Publish charts
          command: |
            case ${CIRCLE_BRANCH} in
              "master_test" | "azure_test" )
                curl -sL https://raw.githubusercontent.com/tompizmor/test-infra/chart_repo_branches/circle/helm-publish-charts.sh | bash -
                ;;
              * )
                echo "Skipping chart publishing for ${CIRCLE_BRANCH} branch"
                ;;
            esac

workflows:
  version: 2
  package-and-publish:
    jobs:
      - package:
          filters:
            branches:
              only: /.*/
